services:
    php:
        # image: php:8.2-apache
        build: .
        volumes:
            - ./web:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini:cached
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
        restart: always
        ports:
            - 8000:80
        container_name: php
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        container_name: mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: test
            MYSQL_ROOT_PASSWORD: test
            PMA_HOST: mysql
volumes:
  db-data:
